 #RESPONSES CONSTANTS
 RESPONSE_OK    = 1
 RESPONSE_ERROR = -1




 RESPONSE_ERROR_USER_ALREADY_EXISTS = -1001
 RESPONSE_ERROR_SENDING_CODE = -1002
 RESPONSE_ERROR_CODE_NOT_CORRECT = -1003

 RESPONSE_ERROR_GROUP_ALREADY_EXISTS = -2001
 RESPONSE_ERROR_CONTACT_NOT_FOUND = -2002
 RESPONSE_ERROR_CONTACT_ALREADY_MEMBER = -2003
 






